terraform {
  required_version = ">= 1.5.0"

  required_providers {
    trocco = {
      source  = "trocco-io/trocco"
      version = "~> 0.24"
    }
  }
}

provider "trocco" {
  api_key = var.trocco_api_key
  region  = "japan" # "india", "korea"
}

# ─── kintone Connection ──────────────────────────────
# kintone_connection_id が設定されている場合: 既存接続を参照
# kintone_connection_id が null の場合: Terraform で新規作成

resource "trocco_connection" "kintone_source" {
  count = var.kintone_connection_id == null ? 1 : 0

  name            = var.kintone_connection_name
  connection_type = "kintone"
  description     = "kintone ${var.kintone_app_name} - auto-generated by NL-to-Pipeline"

  domain       = var.kintone_domain
  login_method = "token"
  token        = var.kintone_api_token
}

# ─── Snowflake Connection ────────────────────────────
# snowflake_connection_id が設定されている場合: 既存接続を参照
# snowflake_connection_id が null の場合: Terraform で新規作成

resource "trocco_connection" "snowflake_dest" {
  count = var.snowflake_connection_id == null ? 1 : 0

  name            = var.snowflake_connection_name
  connection_type = "snowflake"
  description     = "Snowflake ${var.snowflake_database}.${var.snowflake_schema} - auto-generated by NL-to-Pipeline"

  host        = var.snowflake_host
  user_name   = var.snowflake_user
  auth_method = "user_password"
  password    = var.snowflake_password
  role        = var.snowflake_role
}

locals {
  kintone_connection_id = (
    var.kintone_connection_id != null
    ? var.kintone_connection_id
    : trocco_connection.kintone_source[0].id
  )
  snowflake_connection_id = (
    var.snowflake_connection_id != null
    ? var.snowflake_connection_id
    : trocco_connection.snowflake_dest[0].id
  )
}

# ─── Job Definition ──────────────────────────────────

resource "trocco_job_definition" "kintone_to_snowflake" {
  name                     = var.job_name
  description              = var.job_description
  is_runnable_concurrently = false
  retry_limit              = 2

  input_option_type = "kintone"
  input_option = {
    kintone_input_option = {
      kintone_connection_id = local.kintone_connection_id
      app_id                = var.kintone_app_id
      guest_space_id        = var.kintone_guest_space_id
      expand_subtable       = var.kintone_expand_subtable

      input_option_columns = var.input_columns
    }
  }

  output_option_type = "snowflake"
  output_option = {
    snowflake_output_option = {
      snowflake_connection_id = local.snowflake_connection_id
      warehouse               = var.snowflake_warehouse
      database                = var.snowflake_database
      schema                  = var.snowflake_schema
      table                   = var.snowflake_table
      mode                    = var.snowflake_load_mode
    }
  }

  filter_columns = var.filter_columns

  labels = var.labels
}
