# ─── TROCCO ─────────────────────────────────────────

variable "trocco_api_key" {
  description = "TROCCO API Key"
  type        = string
  sensitive   = true
}

# ─── kintone ─────────────────────────────────────────
# モードA: kintone_connection_id を設定 → 既存接続を参照（推奨）
# モードB: kintone_connection_id を null → domain/token で新規作成

variable "kintone_connection_id" {
  description = "Existing TROCCO kintone connection ID. If set, skips connection creation."
  type        = number
  default     = null
}

variable "kintone_connection_name" {
  description = "Connection name in TROCCO (used only when creating new connection)"
  type        = string
  default     = "kintone-auto"
}

variable "kintone_domain" {
  description = "kintone domain (used only when creating new connection)"
  type        = string
  default     = ""
}

variable "kintone_api_token" {
  description = "kintone API token (used only when creating new connection)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "kintone_app_id" {
  description = "kintone app ID"
  type        = string
}

variable "kintone_app_name" {
  description = "kintone app name (for labeling)"
  type        = string
  default     = "kintone-app"
}

variable "kintone_guest_space_id" {
  description = "kintone guest space ID (null if not applicable)"
  type        = string
  default     = null
}

variable "kintone_expand_subtable" {
  description = "Whether to expand subtables"
  type        = bool
  default     = false
}

# ─── Snowflake ───────────────────────────────────────
# モードA: snowflake_connection_id を設定 → 既存接続を参照
# モードB: snowflake_connection_id を null → host/user/password で新規作成

variable "snowflake_connection_id" {
  description = "Existing TROCCO Snowflake connection ID. If set, skips connection creation."
  type        = number
  default     = null
}

variable "snowflake_connection_name" {
  description = "Connection name in TROCCO (used only when creating new connection)"
  type        = string
  default     = "snowflake-auto"
}

variable "snowflake_host" {
  description = "Snowflake host (used only when creating new connection)"
  type        = string
  default     = ""
}

variable "snowflake_user" {
  description = "Snowflake username (used only when creating new connection)"
  type        = string
  default     = ""
}

variable "snowflake_password" {
  description = "Snowflake password (used only when creating new connection)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "snowflake_role" {
  description = "Snowflake role"
  type        = string
  default     = "SYSADMIN"
}

variable "snowflake_warehouse" {
  description = "Snowflake warehouse name"
  type        = string
}

variable "snowflake_database" {
  description = "Snowflake database name"
  type        = string
}

variable "snowflake_schema" {
  description = "Snowflake schema name"
  type        = string
  default     = "PUBLIC"
}

variable "snowflake_table" {
  description = "Snowflake table name"
  type        = string
}

variable "snowflake_load_mode" {
  description = "Load mode (insert, insert_direct, truncate_insert, replace, merge)"
  type        = string
  default     = "replace"
}

# ─── Job Definition ──────────────────────────────────

variable "job_name" {
  description = "Transfer job name"
  type        = string
}

variable "job_description" {
  description = "Transfer job description"
  type        = string
  default     = "Auto-generated by TROCCO Pipeline Builder"
}

variable "input_columns" {
  description = "Input column definitions"
  type = list(object({
    name   = string
    type   = string
    format = optional(string)
  }))
}

variable "filter_columns" {
  description = "Filter column definitions (source → destination mapping)"
  type = list(object({
    name                = string
    src                 = string
    type                = string
    default             = optional(string, "")
    format              = optional(string)
    json_expand_enabled = optional(bool, false)
  }))
}

# ─── Labels ──────────────────────────────────────────

variable "labels" {
  description = "Labels for the job definition"
  type = list(object({
    name = string
  }))
  default = [
    { name = "auto-generated" },
    { name = "trocco-pipeline-builder" }
  ]
}
