terraform {
  required_version = ">= 1.5.0"

  required_providers {
    trocco = {
      source  = "trocco-io/trocco"
      version = "~> 0.24"
    }
  }
}

provider "trocco" {
  api_key = var.trocco_api_key
  region  = "japan" # "india", "korea"
}

# ─── kintone Connection ──────────────────────────────
# kintone_connection_id が設定されている場合: 既存接続を参照（リソース作成をスキップ）
# kintone_connection_id が null の場合: Terraform で新規作成

resource "trocco_connection" "kintone_source" {
  count = var.kintone_connection_id == null ? 1 : 0

  name            = var.kintone_connection_name
  connection_type = "kintone"
  description     = "kintone ${var.kintone_app_name} - auto-generated by NL-to-Pipeline"

  domain       = var.kintone_domain
  login_method = "token"
  token        = var.kintone_api_token
}

locals {
  kintone_connection_id = (
    var.kintone_connection_id != null
    ? var.kintone_connection_id
    : trocco_connection.kintone_source[0].id
  )
}

# ─── Job Definition ──────────────────────────────────
# BigQuery connection is referenced by ID (create via TROCCO UI or API).
# See: reference/destinations/bigquery.md

resource "trocco_job_definition" "kintone_to_bigquery" {
  name                     = var.job_name
  description              = var.job_description
  is_runnable_concurrently = false
  retry_limit              = 2

  input_option_type = "kintone"
  input_option = {
    kintone_input_option = {
      kintone_connection_id = local.kintone_connection_id
      app_id                = var.kintone_app_id
      guest_space_id        = var.kintone_guest_space_id
      expand_subtable       = var.kintone_expand_subtable

      input_option_columns = var.input_columns
    }
  }

  output_option_type = "bigquery"
  output_option = {
    bigquery_output_option = {
      bigquery_connection_id = var.bq_connection_id
      dataset                = var.bq_dataset
      table                  = var.bq_table
      location               = var.bq_location
      mode                   = var.bq_load_mode
      auto_create_dataset    = true
    }
  }

  filter_columns = var.filter_columns

  labels = var.labels
}
